
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/insurance_db
    username: postgres
    password: senha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

insurance:
  providers:
    - name: tokio-marine
      base-url: https://api.tokiomarine.com.br
      token: ${PORTO_TOKEN}
    - name: bradesco
      base-url: https://api.bradesco.com.br
      token: ${BRADESCO_TOKEN}